import type { TemplateMetadata, DriverMetadata } from './marketplace'

// Mock templates data matching marketplace API response format
export const mockTemplates: TemplateMetadata[] = [
  {
    id: 'humidity_sensor',
    name: 'humidity_sensor',
    version: '1.0.0',
    category: 'sensors',
    protocol: 'modbus',
    manufacturer: 'TinyIoT',
    description: '标准湿度传感器设备模板',
    tags: ['sensor', 'humidity', 'monitoring'],
    author: { name: 'TinyIoT', email: 'support@tinyiothub.com' },
    icon: undefined,
    downloads: 1234,
    rating: 4.5,
    reviews: 89,
    license: 'MIT',
    fileUrl: 'https://marketplace.tinyiothub.com/templates/humidity_sensor.json',
    checksum: 'abc123',
    size: 1024,
    createdAt: '2026-01-15T10:00:00Z',
    updatedAt: '2026-03-20T10:00:00Z',
  },
  {
    id: 'temperature_sensor',
    name: 'temperature_sensor',
    version: '1.0.0',
    category: 'sensors',
    protocol: 'modbus',
    manufacturer: 'TinyIoT',
    description: '标准温度传感器设备模板',
    tags: ['sensor', 'temperature', 'monitoring'],
    author: { name: 'TinyIoT', email: 'support@tinyiothub.com' },
    icon: undefined,
    downloads: 2345,
    rating: 4.7,
    reviews: 156,
    license: 'MIT',
    fileUrl: 'https://marketplace.tinyiothub.com/templates/temperature_sensor.json',
    checksum: 'def456',
    size: 1024,
    createdAt: '2026-01-10T10:00:00Z',
    updatedAt: '2026-03-18T10:00:00Z',
  },
  {
    id: 'smart_meter',
    name: 'smart_meter',
    version: '1.0.0',
    category: 'meters',
    protocol: 'modbus',
    manufacturer: 'TinyIoT',
    description: '智能电表设备模板',
    tags: ['meter', 'power', 'energy'],
    author: { name: 'TinyIoT', email: 'support@tinyiothub.com' },
    icon: undefined,
    downloads: 987,
    rating: 4.3,
    reviews: 45,
    license: 'MIT',
    fileUrl: 'https://marketplace.tinyiothub.com/templates/smart_meter.json',
    checksum: 'ghi789',
    size: 1024,
    createdAt: '2026-02-01T10:00:00Z',
    updatedAt: '2026-03-15T10:00:00Z',
  },
  {
    id: 'onvif_camera',
    name: 'onvif_camera',
    version: '1.0.0',
    category: 'cameras',
    protocol: 'onvif',
    manufacturer: 'TinyIoT',
    description: 'ONVIF 网络摄像头模板',
    tags: ['camera', 'onvif', 'video'],
    author: { name: 'TinyIoT', email: 'support@tinyiothub.com' },
    icon: undefined,
    downloads: 3456,
    rating: 4.8,
    reviews: 234,
    license: 'MIT',
    fileUrl: 'https://marketplace.tinyiothub.com/templates/onvif_camera.json',
    checksum: 'jkl012',
    size: 1024,
    createdAt: '2025-12-20T10:00:00Z',
    updatedAt: '2026-03-10T10:00:00Z',
  },
  {
    id: 'mqtt_gateway',
    name: 'mqtt_gateway',
    version: '1.0.0',
    category: 'gateways',
    protocol: 'mqtt',
    manufacturer: 'TinyIoT',
    description: 'MQTT 网关设备模板',
    tags: ['gateway', 'mqtt', 'iot'],
    author: { name: 'TinyIoT', email: 'support@tinyiothub.com' },
    icon: undefined,
    downloads: 4567,
    rating: 4.6,
    reviews: 178,
    license: 'MIT',
    fileUrl: 'https://marketplace.tinyiothub.com/templates/mqtt_gateway.json',
    checksum: 'mno345',
    size: 1024,
    createdAt: '2025-11-15T10:00:00Z',
    updatedAt: '2026-03-05T10:00:00Z',
  },
  {
    id: 'snmp_ups',
    name: 'snmp_ups',
    version: '1.0.0',
    category: 'power',
    protocol: 'snmp',
    manufacturer: 'TinyIoT',
    description: 'SNMP UPS 监控模板',
    tags: ['ups', 'snmp', 'power', 'monitoring'],
    author: { name: 'TinyIoT', email: 'support@tinyiothub.com' },
    icon: undefined,
    downloads: 789,
    rating: 4.4,
    reviews: 56,
    license: 'MIT',
    fileUrl: 'https://marketplace.tinyiothub.com/templates/snmp_ups.json',
    checksum: 'pqr678',
    size: 1024,
    createdAt: '2026-01-25T10:00:00Z',
    updatedAt: '2026-03-01T10:00:00Z',
  },
]

// Mock drivers data
export const mockDrivers: DriverMetadata[] = [
  {
    id: 'driver-001',
    name: 'Modbus RTU Driver',
    version: '1.0.0',
    protocol: 'modbus',
    description: 'Modbus RTU 通信驱动，支持标准 Modbus RTU 协议设备',
    tags: ['modbus', 'rtu', 'industrial'],
    author: { name: 'tinyiothub', email: 'support@tinyiothub.com' },
    icon: undefined,
    downloads: 5678,
    rating: 4.7,
    reviews: 345,
    license: 'MIT',
    homepage: 'https://github.com/tinyiothub/driver-modbus-rtu',
    documentation: 'https://docs.tinyiothub.com/drivers/modbus-rtu',
    platforms: {
      linux: { fileUrl: 'https://marketplace.tinyiothub.com/drivers/modbus_rtu_linux.tar.gz', checksum: 'aaa111', size: 204800 },
      windows: { fileUrl: 'https://marketplace.tinyiothub.com/drivers/modbus_rtu_windows.tar.gz', checksum: 'bbb222', size: 184320 },
    },
    requirements: { minVersion: '1.0.0' },
    createdAt: '2025-06-01T10:00:00Z',
    updatedAt: '2026-03-20T10:00:00Z',
  },
  {
    id: 'driver-002',
    name: 'Modbus TCP Driver',
    version: '1.0.0',
    protocol: 'modbus',
    description: 'Modbus TCP 通信驱动，支持标准 Modbus TCP 协议设备',
    tags: ['modbus', 'tcp', 'industrial'],
    author: { name: 'tinyiothub', email: 'support@tinyiothub.com' },
    icon: undefined,
    downloads: 4567,
    rating: 4.6,
    reviews: 289,
    license: 'MIT',
    homepage: 'https://github.com/tinyiothub/driver-modbus-tcp',
    documentation: 'https://docs.tinyiothub.com/drivers/modbus-tcp',
    platforms: {
      linux: { fileUrl: 'https://marketplace.tinyiothub.com/drivers/modbus_tcp_linux.tar.gz', checksum: 'ccc333', size: 194560 },
      windows: { fileUrl: 'https://marketplace.tinyiothub.com/drivers/modbus_tcp_windows.tar.gz', checksum: 'ddd444', size: 173440 },
    },
    requirements: { minVersion: '1.0.0' },
    createdAt: '2025-06-15T10:00:00Z',
    updatedAt: '2026-03-18T10:00:00Z',
  },
  {
    id: 'driver-003',
    name: 'ONVIF Camera Driver',
    version: '1.0.0',
    protocol: 'onvif',
    description: 'ONVIF 网络摄像头驱动，支持标准 ONVIF 协议摄像头',
    tags: ['onvif', 'camera', 'video', 'rtsp'],
    author: { name: 'tinyiothub', email: 'support@tinyiothub.com' },
    icon: undefined,
    downloads: 3456,
    rating: 4.8,
    reviews: 234,
    license: 'MIT',
    homepage: 'https://github.com/tinyiothub/driver-onvif',
    documentation: 'https://docs.tinyiothub.com/drivers/onvif',
    platforms: {
      linux: { fileUrl: 'https://marketplace.tinyiothub.com/drivers/onvif_linux.tar.gz', checksum: 'eee555', size: 215040 },
      windows: { fileUrl: 'https://marketplace.tinyiothub.com/drivers/onvif_windows.tar.gz', checksum: 'fff666', size: 194560 },
    },
    requirements: { minVersion: '1.0.0' },
    createdAt: '2025-07-01T10:00:00Z',
    updatedAt: '2026-03-15T10:00:00Z',
  },
  {
    id: 'driver-004',
    name: 'SNMP Agent Driver',
    version: '1.0.0',
    protocol: 'snmp',
    description: 'SNMP 代理驱动，支持 SNMP v1/v2c/v3 协议设备',
    tags: ['snmp', 'agent', 'monitoring'],
    author: { name: 'tinyiothub', email: 'support@tinyiothub.com' },
    icon: undefined,
    downloads: 2345,
    rating: 4.5,
    reviews: 167,
    license: 'MIT',
    homepage: 'https://github.com/tinyiothub/driver-snmp',
    documentation: 'https://docs.tinyiothub.com/drivers/snmp',
    platforms: {
      linux: { fileUrl: 'https://marketplace.tinyiothub.com/drivers/snmp_linux.tar.gz', checksum: 'ggg777', size: 184320 },
      windows: { fileUrl: 'https://marketplace.tinyiothub.com/drivers/snmp_windows.tar.gz', checksum: 'hhh888', size: 163840 },
    },
    requirements: { minVersion: '1.0.0' },
    createdAt: '2025-08-01T10:00:00Z',
    updatedAt: '2026-03-10T10:00:00Z',
  },
  {
    id: 'driver-005',
    name: 'MQTT Client Driver',
    version: '1.0.0',
    protocol: 'mqtt',
    description: 'MQTT 客户端驱动，支持 MQTT 3.1.1/5.0 协议',
    tags: ['mqtt', 'client', 'pub-sub', 'iot'],
    author: { name: 'tinyiothub', email: 'support@tinyiothub.com' },
    icon: undefined,
    downloads: 6789,
    rating: 4.9,
    reviews: 456,
    license: 'MIT',
    homepage: 'https://github.com/tinyiothub/driver-mqtt',
    documentation: 'https://docs.tinyiothub.com/drivers/mqtt',
    platforms: {
      linux: { fileUrl: 'https://marketplace.tinyiothub.com/drivers/mqtt_linux.tar.gz', checksum: 'iii999', size: 204800 },
      windows: { fileUrl: 'https://marketplace.tinyiothub.com/drivers/mqtt_windows.tar.gz', checksum: 'jjj000', size: 184320 },
    },
    requirements: { minVersion: '1.0.0' },
    createdAt: '2025-05-15T10:00:00Z',
    updatedAt: '2026-03-25T10:00:00Z',
  },
]
