[package]
name = "integration-tests"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
tinyiothub-cloud = { path = "../../apps/cloud", features = ["test-utils"] }
db = { workspace = true }
sqlx = { workspace = true }
tokio = { workspace = true, features = ["full"] }
uuid = { workspace = true }

[lints]
workspace = true
