//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "apps")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub llms: Option<String>,
    pub status: String,
    pub is_public: bool,
    pub is_demo: bool,
    pub mode: Option<String>,
    pub icon_type: Option<String>,
    pub icon: Option<String>,
    pub icon_background: Option<String>,
    pub enable_site: bool,
    pub enable_api: bool,
    pub api_rpm: i32,
    pub api_rph: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub tracing: Option<String>,
    pub site: Option<Json>,
    pub api_base_url: Option<String>,
    pub tags: Option<Json>,
    pub access_mode: Option<String>,
    pub tenant_id: i32,
    pub created_by: i32,
    pub updated_by: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::tag_bindings::Entity")]
    TagBindings,
    #[sea_orm(
        belongs_to = "super::tenants::Entity",
        from = "Column::TenantId",
        to = "super::tenants::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Tenants,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UpdatedBy",
        to = "super::users::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Users2,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::CreatedBy",
        to = "super::users::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Users1,
}

impl Related<super::tag_bindings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TagBindings.def()
    }
}

impl Related<super::tenants::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tenants.def()
    }
}
