//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "devices")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub description: Option<String>,
    pub kind: Option<String>,
    pub config: Option<Json>,
    pub network_config: Option<Json>,
    pub security_config: Option<Json>,
    pub last_seen: Option<DateTimeWithTimeZone>,
    pub is_active: bool,
    pub status: i32,
    pub extensions: Option<Json>,
    pub tenant_id: i32,
    pub created_by: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::device_events::Entity")]
    DeviceEvents,
    #[sea_orm(has_many = "super::device_properties::Entity")]
    DeviceProperties,
    #[sea_orm(has_many = "super::device_service_calls::Entity")]
    DeviceServiceCalls,
    #[sea_orm(
        belongs_to = "super::tenants::Entity",
        from = "Column::TenantId",
        to = "super::tenants::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Tenants,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::CreatedBy",
        to = "super::users::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::device_events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DeviceEvents.def()
    }
}

impl Related<super::device_properties::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DeviceProperties.def()
    }
}

impl Related<super::device_service_calls::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DeviceServiceCalls.def()
    }
}

impl Related<super::tenants::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tenants.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}
