//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "devices")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub name: String,
    pub description: Option<String>,
    pub kind: Option<String>,
    pub config: Option<Json>,
    pub network_config: Option<Json>,
    pub security_config: Option<Json>,
    pub last_seen: Option<DateTimeWithTimeZone>,
    pub is_active: bool,
    pub status: i32,
    pub extensions: Option<Json>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::device_events::Entity")]
    DeviceEvents,
    #[sea_orm(has_many = "super::device_properties::Entity")]
    DeviceProperties,
    #[sea_orm(has_many = "super::device_service_calls::Entity")]
    DeviceServiceCalls,
}

impl Related<super::device_events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DeviceEvents.def()
    }
}

impl Related<super::device_properties::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DeviceProperties.def()
    }
}

impl Related<super::device_service_calls::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DeviceServiceCalls.def()
    }
}
