//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

pub use super::apps::Entity as Apps;
pub use super::device_events::Entity as DeviceEvents;
pub use super::device_properties::Entity as DeviceProperties;
pub use super::device_service_calls::Entity as DeviceServiceCalls;
pub use super::device_templates::Entity as DeviceTemplates;
pub use super::devices::Entity as Devices;
pub use super::tag_bindings::Entity as TagBindings;
pub use super::tags::Entity as Tags;
pub use super::tenants::Entity as Tenants;
pub use super::users::Entity as Users;
