-- Seed builtin templates into device_templates table.
-- Uses INSERT OR IGNORE for idempotency — safe to run multiple times.
-- IDs match the pattern generated by DeviceTemplate::from_request().

INSERT OR IGNORE INTO device_templates (id, name, display_name, description, version, author, category, manufacturer, device_type, protocol_type, driver_name, tags, device_info, properties, commands, is_builtin, is_active, created_at, updated_at)
VALUES
(
    'builtin_temperature_humidity_sensor',
    'temperature_humidity_sensor',
    '{"zh":"温湿度传感器","en":"Temperature & Humidity Sensor"}',
    '{"zh":"高精度温湿度传感器，适用于机房、仓库、农业大棚等场景","en":"High-precision temperature and humidity sensor, suitable for server rooms, warehouses, greenhouses"}',
    '1.0.0', 'TinyIoT', 'sensors', 'TinyIoT', 'sensor', 'modbus', 'modbus_rtu',
    '["temperature","humidity","environment"]',
    '{"default_name_pattern":"th_sensor_{index}","default_display_name_pattern":{"zh":"温湿度传感器 {index}","en":"Temp & Humidity Sensor {index}"},"required_fields":["name","address"]}',
    '[{"name":"temperature","display_name":{"zh":"温度","en":"Temperature"},"description":{"zh":"环境温度","en":"Ambient temperature"},"data_type":"number","unit":"°C","min_value":-40.0,"max_value":80.0,"default_value":"25.0","is_read_only":true,"is_required":true},{"name":"humidity","display_name":{"zh":"湿度","en":"Humidity"},"description":{"zh":"相对湿度","en":"Relative humidity"},"data_type":"number","unit":"%RH","min_value":0.0,"max_value":100.0,"default_value":"50.0","is_read_only":true,"is_required":true},{"name":"dew_point","display_name":{"zh":"露点温度","en":"Dew Point"},"description":{"zh":"露点温度","en":"Dew point temperature"},"data_type":"number","unit":"°C","min_value":-40.0,"max_value":80.0,"default_value":"15.0","is_read_only":true,"is_required":false}]',
    '[{"name":"read_all","display_name":{"zh":"读取全部","en":"Read All"},"description":{"zh":"读取温湿度数据","en":"Read temperature and humidity data"},"parameters":"{}","is_required":true}]',
    1, 1, '2024-01-01 00:00:00', '2024-01-01 00:00:00'
),
(
    'builtin_power_meter',
    'power_meter',
    '{"zh":"电力仪表","en":"Power Meter"}',
    '{"zh":"多功能电力仪表，监测电压、电流、功率、电量，适用于配电柜、能耗监测","en":"Multi-function power meter, monitors voltage, current, power, energy, for distribution panels and energy monitoring"}',
    '1.0.0', 'TinyIoT', 'sensors', 'TinyIoT', 'sensor', 'modbus', 'modbus_rtu',
    '["power","energy","electricity","meter"]',
    '{"default_name_pattern":"power_meter_{index}","default_display_name_pattern":{"zh":"电力仪表 {index}","en":"Power Meter {index}"},"required_fields":["name","address"]}',
    '[{"name":"voltage","display_name":{"zh":"电压","en":"Voltage"},"description":{"zh":"相电压","en":"Phase voltage"},"data_type":"number","unit":"V","min_value":0.0,"max_value":500.0,"default_value":"220.0","is_read_only":true,"is_required":true},{"name":"current","display_name":{"zh":"电流","en":"Current"},"description":{"zh":"相电流","en":"Phase current"},"data_type":"number","unit":"A","min_value":0.0,"max_value":1000.0,"default_value":"10.0","is_read_only":true,"is_required":true},{"name":"active_power","display_name":{"zh":"有功功率","en":"Active Power"},"description":{"zh":"有功功率","en":"Active power"},"data_type":"number","unit":"kW","min_value":0.0,"max_value":999999.0,"default_value":"2.2","is_read_only":true,"is_required":true},{"name":"energy","display_name":{"zh":"累计电量","en":"Total Energy"},"description":{"zh":"累计用电量","en":"Total energy consumption"},"data_type":"number","unit":"kWh","min_value":0.0,"max_value":99999999.0,"default_value":"0.0","is_read_only":true,"is_required":true},{"name":"power_factor","display_name":{"zh":"功率因数","en":"Power Factor"},"description":{"zh":"功率因数","en":"Power factor"},"data_type":"number","unit":"","min_value":-1.0,"max_value":1.0,"default_value":"0.95","is_read_only":true,"is_required":false},{"name":"frequency","display_name":{"zh":"频率","en":"Frequency"},"description":{"zh":"电网频率","en":"Grid frequency"},"data_type":"number","unit":"Hz","min_value":45.0,"max_value":65.0,"default_value":"50.0","is_read_only":true,"is_required":false}]',
    '[{"name":"read_all","display_name":{"zh":"读取全部","en":"Read All"},"description":{"zh":"读取所有电力参数","en":"Read all power parameters"},"parameters":"{}","is_required":true},{"name":"reset_energy","display_name":{"zh":"电量清零","en":"Reset Energy"},"description":{"zh":"重置累计电量","en":"Reset total energy counter"},"parameters":"{}","is_required":false}]',
    1, 1, '2024-01-01 00:00:00', '2024-01-01 00:00:00'
),
(
    'builtin_water_level_sensor',
    'water_level_sensor',
    '{"zh":"液位传感器","en":"Water Level Sensor"}',
    '{"zh":"投入式液位传感器，适用于水箱、水池、河道水位监测","en":"Submersible level sensor, suitable for tanks, pools, river level monitoring"}',
    '1.0.0', 'TinyIoT', 'sensors', 'TinyIoT', 'sensor', 'modbus', 'modbus_rtu',
    '["water","level","liquid","tank"]',
    '{"default_name_pattern":"water_level_{index}","default_display_name_pattern":{"zh":"液位传感器 {index}","en":"Water Level Sensor {index}"},"required_fields":["name","address"]}',
    '[{"name":"level","display_name":{"zh":"液位","en":"Level"},"description":{"zh":"当前液位高度","en":"Current liquid level"},"data_type":"number","unit":"m","min_value":0.0,"max_value":10.0,"default_value":"1.5","is_read_only":true,"is_required":true},{"name":"level_percent","display_name":{"zh":"液位百分比","en":"Level Percentage"},"description":{"zh":"液位百分比","en":"Level percentage"},"data_type":"number","unit":"%","min_value":0.0,"max_value":100.0,"default_value":"50.0","is_read_only":true,"is_required":true},{"name":"temperature","display_name":{"zh":"液体温度","en":"Liquid Temperature"},"description":{"zh":"液体温度","en":"Liquid temperature"},"data_type":"number","unit":"°C","min_value":-10.0,"max_value":80.0,"default_value":"20.0","is_read_only":true,"is_required":false}]',
    '[{"name":"read_all","display_name":{"zh":"读取全部","en":"Read All"},"description":{"zh":"读取液位数据","en":"Read level data"},"parameters":"{}","is_required":true}]',
    1, 1, '2024-01-01 00:00:00', '2024-01-01 00:00:00'
),
(
    'builtin_air_quality_sensor',
    'air_quality_sensor',
    '{"zh":"空气质量传感器","en":"Air Quality Sensor"}',
    '{"zh":"多合一空气质量传感器，监测PM2.5、CO2、温度、湿度，适用于智慧楼宇","en":"Multi-in-one air quality sensor, monitors PM2.5, CO2, temperature, humidity, for smart buildings"}',
    '1.0.0', 'TinyIoT', 'sensors', 'TinyIoT', 'sensor', 'modbus', 'modbus_rtu',
    '["air","quality","pm25","co2","indoor"]',
    '{"default_name_pattern":"air_quality_{index}","default_display_name_pattern":{"zh":"空气质量传感器 {index}","en":"Air Quality Sensor {index}"},"required_fields":["name","address"]}',
    '[{"name":"pm25","display_name":{"zh":"PM2.5","en":"PM2.5"},"description":{"zh":"细颗粒物浓度","en":"PM2.5 concentration"},"data_type":"number","unit":"μg/m³","min_value":0.0,"max_value":1000.0,"default_value":"35.0","is_read_only":true,"is_required":true},{"name":"pm10","display_name":{"zh":"PM10","en":"PM10"},"description":{"zh":"可吸入颗粒物浓度","en":"PM10 concentration"},"data_type":"number","unit":"μg/m³","min_value":0.0,"max_value":1000.0,"default_value":"50.0","is_read_only":true,"is_required":false},{"name":"co2","display_name":{"zh":"CO2浓度","en":"CO2 Level"},"description":{"zh":"二氧化碳浓度","en":"Carbon dioxide concentration"},"data_type":"number","unit":"ppm","min_value":400.0,"max_value":5000.0,"default_value":"400.0","is_read_only":true,"is_required":true},{"name":"temperature","display_name":{"zh":"温度","en":"Temperature"},"description":{"zh":"环境温度","en":"Ambient temperature"},"data_type":"number","unit":"°C","min_value":-20.0,"max_value":60.0,"default_value":"25.0","is_read_only":true,"is_required":true},{"name":"humidity","display_name":{"zh":"湿度","en":"Humidity"},"description":{"zh":"相对湿度","en":"Relative humidity"},"data_type":"number","unit":"%RH","min_value":0.0,"max_value":100.0,"default_value":"50.0","is_read_only":true,"is_required":true},{"name":"tvoc","display_name":{"zh":"TVOC","en":"TVOC"},"description":{"zh":"总挥发性有机化合物","en":"Total volatile organic compounds"},"data_type":"number","unit":"ppb","min_value":0.0,"max_value":50000.0,"default_value":"220.0","is_read_only":true,"is_required":false},{"name":"aqi","display_name":{"zh":"AQI","en":"AQI"},"description":{"zh":"空气质量指数","en":"Air quality index"},"data_type":"number","unit":"","min_value":0.0,"max_value":500.0,"default_value":"50.0","is_read_only":true,"is_required":true}]',
    '[{"name":"read_all","display_name":{"zh":"读取全部","en":"Read All"},"description":{"zh":"读取所有空气质量数据","en":"Read all air quality data"},"parameters":"{}","is_required":true},{"name":"calibrate","display_name":{"zh":"校准","en":"Calibrate"},"description":{"zh":"执行传感器校准","en":"Execute sensor calibration"},"parameters":"{\"sensor\": \"co2\"}","parameter_schema":"{\"type\": \"object\", \"properties\": {\"sensor\": {\"type\": \"string\", \"enum\": [\"pm25\", \"co2\", \"tvoc\"]}}, \"required\": [\"sensor\"]}","is_required":false}]',
    1, 1, '2024-01-01 00:00:00', '2024-01-01 00:00:00'
),
(
    'builtin_ip_camera',
    'ip_camera',
    '{"zh":"网络摄像头","en":"IP Camera"}',
    '{"zh":"ONVIF协议网络摄像头，支持RTSP流、PTZ控制、移动侦测","en":"ONVIF IP camera, supports RTSP streaming, PTZ control, motion detection"}',
    '1.0.0', 'TinyIoT', 'cameras', 'Generic', 'camera', 'onvif', 'onvif',
    '["camera","video","surveillance","onvif"]',
    '{"default_name_pattern":"camera_{index}","default_display_name_pattern":{"zh":"摄像头 {index}","en":"IP Camera {index}"},"required_fields":["name","address"]}',
    '[{"name":"rtsp_url","display_name":{"zh":"RTSP地址","en":"RTSP URL"},"description":{"zh":"视频流地址","en":"Video stream URL"},"data_type":"string","unit":"","default_value":"","is_read_only":true,"is_required":true},{"name":"resolution","display_name":{"zh":"分辨率","en":"Resolution"},"description":{"zh":"视频分辨率","en":"Video resolution"},"data_type":"string","unit":"","default_value":"1920x1080","is_read_only":true,"is_required":false},{"name":"motion_detected","display_name":{"zh":"移动侦测","en":"Motion Detected"},"description":{"zh":"是否检测到移动","en":"Whether motion is detected"},"data_type":"boolean","unit":"","default_value":"false","is_read_only":true,"is_required":false},{"name":"ptz_pan","display_name":{"zh":"水平角度","en":"Pan Angle"},"description":{"zh":"PTZ水平角度","en":"PTZ pan angle"},"data_type":"number","unit":"°","min_value":-180.0,"max_value":180.0,"default_value":"0","is_read_only":false,"is_required":false},{"name":"ptz_tilt","display_name":{"zh":"俯仰角度","en":"Tilt Angle"},"description":{"zh":"PTZ俯仰角度","en":"PTZ tilt angle"},"data_type":"number","unit":"°","min_value":-90.0,"max_value":90.0,"default_value":"0","is_read_only":false,"is_required":false}]',
    '[{"name":"snapshot","display_name":{"zh":"截图","en":"Snapshot"},"description":{"zh":"抓取当前画面","en":"Capture current frame"},"parameters":"{}","is_required":true},{"name":"ptz_move","display_name":{"zh":"PTZ移动","en":"PTZ Move"},"description":{"zh":"控制云台移动","en":"Control PTZ movement"},"parameters":"{\"direction\": \"left\"}","parameter_schema":"{\"type\": \"object\", \"properties\": {\"direction\": {\"type\": \"string\", \"enum\": [\"left\", \"right\", \"up\", \"down\", \"stop\"]}}, \"required\": [\"direction\"]}","is_required":false},{"name":"ptz_home","display_name":{"zh":"回到原点","en":"PTZ Home"},"description":{"zh":"云台回到初始位置","en":"Move PTZ to home position"},"parameters":"{}","is_required":false}]',
    1, 1, '2024-01-01 00:00:00', '2024-01-01 00:00:00'
),
(
    'builtin_agv_robot',
    'agv_robot',
    '{"zh":"AGV搬运机器人","en":"AGV Robot"}',
    '{"zh":"自动导引搬运车，支持任务调度、状态监控、电量管理","en":"Automated Guided Vehicle, supports task dispatch, status monitoring, battery management"}',
    '1.0.0', 'TinyIoT', 'robots', 'Generic', 'robot', 'mqtt', 'mqtt',
    '["agv","robot","logistics","transport"]',
    '{"default_name_pattern":"agv_{index}","default_display_name_pattern":{"zh":"AGV机器人 {index}","en":"AGV Robot {index}"},"required_fields":["name","address"]}',
    '[{"name":"status","display_name":{"zh":"运行状态","en":"Status"},"description":{"zh":"当前运行状态","en":"Current running status"},"data_type":"string","unit":"","default_value":"idle","is_read_only":true,"is_required":true},{"name":"battery_level","display_name":{"zh":"电量","en":"Battery Level"},"description":{"zh":"电池电量百分比","en":"Battery level percentage"},"data_type":"number","unit":"%","min_value":0.0,"max_value":100.0,"default_value":"80.0","is_read_only":true,"is_required":true},{"name":"position_x","display_name":{"zh":"X坐标","en":"X Position"},"description":{"zh":"当前X坐标","en":"Current X position"},"data_type":"number","unit":"m","min_value":-100.0,"max_value":100.0,"default_value":"0.0","is_read_only":true,"is_required":true},{"name":"position_y","display_name":{"zh":"Y坐标","en":"Y Position"},"description":{"zh":"当前Y坐标","en":"Current Y position"},"data_type":"number","unit":"m","min_value":-100.0,"max_value":100.0,"default_value":"0.0","is_read_only":true,"is_required":true},{"name":"speed","display_name":{"zh":"速度","en":"Speed"},"description":{"zh":"当前移动速度","en":"Current movement speed"},"data_type":"number","unit":"m/s","min_value":0.0,"max_value":5.0,"default_value":"0.0","is_read_only":true,"is_required":false},{"name":"current_task","display_name":{"zh":"当前任务","en":"Current Task"},"description":{"zh":"当前执行的任务ID","en":"Current task ID"},"data_type":"string","unit":"","default_value":"","is_read_only":true,"is_required":false}]',
    '[{"name":"move_to","display_name":{"zh":"移动到","en":"Move To"},"description":{"zh":"移动到指定坐标","en":"Move to specified position"},"parameters":"{\"x\": 10.0, \"y\": 5.0}","parameter_schema":"{\"type\": \"object\", \"properties\": {\"x\": {\"type\": \"number\"}, \"y\": {\"type\": \"number\"}}, \"required\": [\"x\", \"y\"]}","is_required":true},{"name":"stop","display_name":{"zh":"停止","en":"Stop"},"description":{"zh":"立即停止移动","en":"Stop movement immediately"},"parameters":"{}","is_required":true},{"name":"charge","display_name":{"zh":"回充电桩","en":"Return to Charge"},"description":{"zh":"返回充电桩充电","en":"Return to charging station"},"parameters":"{}","is_required":false}]',
    1, 1, '2024-01-01 00:00:00', '2024-01-01 00:00:00'
),
(
    'builtin_plc_controller',
    'plc_controller',
    '{"zh":"PLC控制器","en":"PLC Controller"}',
    '{"zh":"Modbus协议PLC控制器，适用于工业自动化、产线控制","en":"Modbus PLC controller, suitable for industrial automation and production line control"}',
    '1.0.0', 'TinyIoT', 'controllers', 'Generic', 'controller', 'modbus', 'modbus_rtu',
    '["plc","controller","industrial","automation"]',
    '{"default_name_pattern":"plc_{index}","default_display_name_pattern":{"zh":"PLC控制器 {index}","en":"PLC Controller {index}"},"required_fields":["name","address"]}',
    '[{"name":"run_status","display_name":{"zh":"运行状态","en":"Run Status"},"description":{"zh":"PLC运行状态","en":"PLC running status"},"data_type":"string","unit":"","default_value":"running","is_read_only":true,"is_required":true},{"name":"error_code","display_name":{"zh":"错误码","en":"Error Code"},"description":{"zh":"当前错误码","en":"Current error code"},"data_type":"integer","unit":"","min_value":0,"max_value":9999,"default_value":"0","is_read_only":true,"is_required":true},{"name":"cycle_time","display_name":{"zh":"扫描周期","en":"Cycle Time"},"description":{"zh":"程序扫描周期","en":"Program scan cycle time"},"data_type":"number","unit":"ms","min_value":0.0,"max_value":10000.0,"default_value":"10.0","is_read_only":true,"is_required":false},{"name":"input_1","display_name":{"zh":"输入点1","en":"Input 1"},"description":{"zh":"数字输入点1","en":"Digital input 1"},"data_type":"boolean","unit":"","default_value":"false","is_read_only":true,"is_required":false},{"name":"output_1","display_name":{"zh":"输出点1","en":"Output 1"},"description":{"zh":"数字输出点1","en":"Digital output 1"},"data_type":"boolean","unit":"","default_value":"false","is_read_only":false,"is_required":false}]',
    '[{"name":"read_status","display_name":{"zh":"读取状态","en":"Read Status"},"description":{"zh":"读取PLC运行状态","en":"Read PLC running status"},"parameters":"{}","is_required":true},{"name":"start","display_name":{"zh":"启动","en":"Start"},"description":{"zh":"启动PLC程序","en":"Start PLC program"},"parameters":"{}","is_required":false},{"name":"stop","display_name":{"zh":"停止","en":"Stop"},"description":{"zh":"停止PLC程序","en":"Stop PLC program"},"parameters":"{}","is_required":false},{"name":"reset","display_name":{"zh":"复位","en":"Reset"},"description":{"zh":"复位PLC错误","en":"Reset PLC error"},"parameters":"{}","is_required":false}]',
    1, 1, '2024-01-01 00:00:00', '2024-01-01 00:00:00'
),
(
    'builtin_smart_relay',
    'smart_relay',
    '{"zh":"智能继电器","en":"Smart Relay"}',
    '{"zh":"多路智能继电器模块，支持远程开关控制，适用于照明、门禁、设备启停","en":"Multi-channel smart relay module, supports remote on/off control, for lighting, access control, device switching"}',
    '1.0.0', 'TinyIoT', 'controllers', 'TinyIoT', 'controller', 'modbus', 'modbus_rtu',
    '["relay","switch","control","lighting"]',
    '{"default_name_pattern":"relay_{index}","default_display_name_pattern":{"zh":"智能继电器 {index}","en":"Smart Relay {index}"},"required_fields":["name","address"]}',
    '[{"name":"channel_1","display_name":{"zh":"通道1","en":"Channel 1"},"description":{"zh":"继电器通道1状态","en":"Relay channel 1 status"},"data_type":"boolean","unit":"","default_value":"false","is_read_only":false,"is_required":true},{"name":"channel_2","display_name":{"zh":"通道2","en":"Channel 2"},"description":{"zh":"继电器通道2状态","en":"Relay channel 2 status"},"data_type":"boolean","unit":"","default_value":"false","is_read_only":false,"is_required":true},{"name":"channel_3","display_name":{"zh":"通道3","en":"Channel 3"},"description":{"zh":"继电器通道3状态","en":"Relay channel 3 status"},"data_type":"boolean","unit":"","default_value":"false","is_read_only":false,"is_required":false},{"name":"channel_4","display_name":{"zh":"通道4","en":"Channel 4"},"description":{"zh":"继电器通道4状态","en":"Relay channel 4 status"},"data_type":"boolean","unit":"","default_value":"false","is_read_only":false,"is_required":false}]',
    '[{"name":"set_channel","display_name":{"zh":"设置通道","en":"Set Channel"},"description":{"zh":"设置指定通道开关状态","en":"Set specified channel on/off"},"parameters":"{\"channel\": 1, \"value\": true}","parameter_schema":"{\"type\": \"object\", \"properties\": {\"channel\": {\"type\": \"integer\", \"minimum\": 1, \"maximum\": 4}, \"value\": {\"type\": \"boolean\"}}, \"required\": [\"channel\", \"value\"]}","is_required":true},{"name":"all_off","display_name":{"zh":"全部关闭","en":"All Off"},"description":{"zh":"关闭所有通道","en":"Turn off all channels"},"parameters":"{}","is_required":false}]',
    1, 1, '2024-01-01 00:00:00', '2024-01-01 00:00:00'
);
